check release version

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -20,6 +20,12 @@ jobs:
   release:
     runs-on: ubuntu-latest
     steps:
+      - name: Check release version
+        if: inputs.release_version != 'auto' && inputs.development_version == 'auto'
+        run: |
+          echo "ERROR: If release version is not auto then next development version must also be provided."
+          exit 1
+
       - name: Checkout source code
         uses: actions/checkout@v2
         with:
